version: '3.8'

services:
  api_youtube_sharing_app_dev:
    container_name: api_youtube_sharing_app_dev
    image: api_youtube_sharing_app_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - youtube_sharing_app_mongodb # Make sure mongo DB started before run container API 
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

  youtube_sharing_app_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} # 2 variables from .env
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD} # use --env-file to read from .env.dev
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  youtube_sharing_app_mongo_express:
    container_name: youtube_sharing_app_mongo_express
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME} # 2 basic variable
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD} # auth when login mongo_express
      ME_CONFIG_MONGODB_URL: ${DATABASE_URI}?authSource=admin # This is Database connection 
    ports:
      - 8002:8081
    depends_on:
      - youtube_sharing_app_mongodb
    restart: unless-stopped

networks:
  default:
    driver: bridge
